*** Settings ***
Documentation    Set variables defined

*** Variables ***
${CoreType}             Core
${ExpansionType}        Expansion
${DraftType}            Draft_Innovation
${CommanderType}        Commander
${FunnyType}            Funny
${MastersType}          Masters

${CoreButton}           //button[@id='mat-button-toggle-2-button']
${ExpansionButton}      //button[@id='mat-button-toggle-3-button']
${DraftButton}          //button[@id='mat-button-toggle-4-button']
${CommanderButton}      //button[@id='mat-button-toggle-5-button']
${FunnyButton}          //button[@id='mat-button-toggle-6-button']
${MastersButton}        //button[@id='mat-button-toggle-7-button']
